from enum import Enum

class AnalyticEvent(str, Enum):
    SEMANTIC_ROUTING = "SEMANTIC ROUTING"
    RAG_HIT = "RAG HIT"
    RAG_MISS = "RAG MISS"
    TOOL_CALL = "TOOL CALL"
    TOOL_FAILURE = "TOOL FAILURE"
    TOOL_ITERATION_LIMIT = "TOOL ITERATION LIMIT REACHED"
    DOCUMENT_INDEXED = "DOCUMENT INDEXED"
    DOCUMENT_INDEXING_FAILED = "DOCUMENT INDEXING FAILED"
    MESSAGE_TURN = "MESSAGE TURN"

class AIProviderType(str, Enum):
    OPENAI = "openai"
    GEMINI = "gemini"
    AZURE_OPENAI = "azure"
