from fastapi import status

class ErrorCode:
    AGENT_NOT_FOUND = "AGENT.NOT_FOUND"
    AUTH_INTERNAL_SECRET_INVALID = "AUTH.INTERNAL_SECRET_INVALID"
    AGENT_CORE_LLM_TIMEOUT = "AGENT_CORE.LLM_TIMEOUT"
    AGENT_CORE_LLM_UNAVAILABLE = "AGENT_CORE.LLM_UNAVAILABLE"
    VALIDATION_FAILED = "VALIDATION.FAILED"
    RESOURCE_NOT_FOUND = "RESOURCE.NOT_FOUND"
    RESOURCE_CONFLICT = "RESOURCE.CONFLICT"
    INTERNAL_UNEXPECTED = "INTERNAL.UNEXPECTED"

DEFAULT_ERROR_CODE_BY_STATUS: dict[int, str] = {
    status.HTTP_400_BAD_REQUEST: ErrorCode.VALIDATION_FAILED,
    status.HTTP_401_UNAUTHORIZED: ErrorCode.AUTH_INTERNAL_SECRET_INVALID,
    status.HTTP_403_FORBIDDEN: ErrorCode.AUTH_INTERNAL_SECRET_INVALID,
    status.HTTP_404_NOT_FOUND: ErrorCode.RESOURCE_NOT_FOUND,
    status.HTTP_409_CONFLICT: ErrorCode.RESOURCE_CONFLICT,
    status.HTTP_422_UNPROCESSABLE_ENTITY: ErrorCode.VALIDATION_FAILED,
}


def default_error_code_for_status(status_code: int) -> str:
    return DEFAULT_ERROR_CODE_BY_STATUS.get(status_code, ErrorCode.INTERNAL_UNEXPECTED)